/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteTaskRequest
 */
export interface DeleteTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof DeleteTaskRequest
     */
    taskId: string;
}

/**
 * Check if a given object implements the DeleteTaskRequest interface.
 */
export function instanceOfDeleteTaskRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskId" in value;

    return isInstance;
}

export function DeleteTaskRequestFromJSON(json: any): DeleteTaskRequest {
    return DeleteTaskRequestFromJSONTyped(json, false);
}

export function DeleteTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteTaskRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': json['task_id'],
    };
}

export function DeleteTaskRequestToJSON(value?: DeleteTaskRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_id': value.taskId,
    };
}

