/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TaskModel } from './TaskModel';
import {
    TaskModelFromJSON,
    TaskModelFromJSONTyped,
    TaskModelToJSON,
} from './TaskModel';

/**
 * 
 * @export
 * @interface GetTasksResponse
 */
export interface GetTasksResponse {
    /**
     * 
     * @type {Array<TaskModel>}
     * @memberof GetTasksResponse
     */
    tasks: Array<TaskModel>;
}

/**
 * Check if a given object implements the GetTasksResponse interface.
 */
export function instanceOfGetTasksResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "tasks" in value;

    return isInstance;
}

export function GetTasksResponseFromJSON(json: any): GetTasksResponse {
    return GetTasksResponseFromJSONTyped(json, false);
}

export function GetTasksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTasksResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tasks': ((json['tasks'] as Array<any>).map(TaskModelFromJSON)),
    };
}

export function GetTasksResponseToJSON(value?: GetTasksResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tasks': ((value.tasks as Array<any>).map(TaskModelToJSON)),
    };
}

