/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToggleTaskCompleteRequest
 */
export interface ToggleTaskCompleteRequest {
    /**
     * 
     * @type {string}
     * @memberof ToggleTaskCompleteRequest
     */
    taskId: string;
    /**
     * 
     * @type {Date}
     * @memberof ToggleTaskCompleteRequest
     */
    completed: Date | null;
}

/**
 * Check if a given object implements the ToggleTaskCompleteRequest interface.
 */
export function instanceOfToggleTaskCompleteRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskId" in value;
    isInstance = isInstance && "completed" in value;

    return isInstance;
}

export function ToggleTaskCompleteRequestFromJSON(json: any): ToggleTaskCompleteRequest {
    return ToggleTaskCompleteRequestFromJSONTyped(json, false);
}

export function ToggleTaskCompleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToggleTaskCompleteRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': json['task_id'],
        'completed': (json['completed'] === null ? null : new Date(json['completed'])),
    };
}

export function ToggleTaskCompleteRequestToJSON(value?: ToggleTaskCompleteRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_id': value.taskId,
        'completed': (value.completed === null ? null : value.completed.toISOString()),
    };
}

