/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTaskCompletedDateRequest
 */
export interface UpdateTaskCompletedDateRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskCompletedDateRequest
     */
    taskId: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateTaskCompletedDateRequest
     */
    completedDate: Date | null;
}

/**
 * Check if a given object implements the UpdateTaskCompletedDateRequest interface.
 */
export function instanceOfUpdateTaskCompletedDateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "taskId" in value;
    isInstance = isInstance && "completedDate" in value;

    return isInstance;
}

export function UpdateTaskCompletedDateRequestFromJSON(json: any): UpdateTaskCompletedDateRequest {
    return UpdateTaskCompletedDateRequestFromJSONTyped(json, false);
}

export function UpdateTaskCompletedDateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskCompletedDateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'taskId': json['task_id'],
        'completedDate': (json['completed_date'] === null ? null : new Date(json['completed_date'])),
    };
}

export function UpdateTaskCompletedDateRequestToJSON(value?: UpdateTaskCompletedDateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'task_id': value.taskId,
        'completed_date': (value.completedDate === null ? null : value.completedDate.toISOString()),
    };
}

