/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateTaskRequest,
  DeleteTaskRequest,
  GetTasksResponse,
  HTTPValidationError,
  UpdateTaskCompletedDateRequest,
  UpdateTaskNameRequest,
} from '../models/index';
import {
    CreateTaskRequestFromJSON,
    CreateTaskRequestToJSON,
    DeleteTaskRequestFromJSON,
    DeleteTaskRequestToJSON,
    GetTasksResponseFromJSON,
    GetTasksResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UpdateTaskCompletedDateRequestFromJSON,
    UpdateTaskCompletedDateRequestToJSON,
    UpdateTaskNameRequestFromJSON,
    UpdateTaskNameRequestToJSON,
} from '../models/index';

export interface CreateTaskOperationRequest {
    createTaskRequest: CreateTaskRequest;
}

export interface DeleteTaskOperationRequest {
    deleteTaskRequest: DeleteTaskRequest;
}

export interface UpdateTaskCompletedDateOperationRequest {
    updateTaskCompletedDateRequest: UpdateTaskCompletedDateRequest;
}

export interface UpdateTaskNameOperationRequest {
    updateTaskNameRequest: UpdateTaskNameRequest;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Create Task
     */
    async createTaskRaw(requestParameters: CreateTaskOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.createTaskRequest === null || requestParameters.createTaskRequest === undefined) {
            throw new runtime.RequiredError('createTaskRequest','Required parameter requestParameters.createTaskRequest was null or undefined when calling createTask.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tasks/create`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTaskRequestToJSON(requestParameters.createTaskRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create Task
     */
    async createTask(requestParameters: CreateTaskOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createTaskRaw(requestParameters, initOverrides);
    }

    /**
     * Delete Task
     */
    async deleteTaskRaw(requestParameters: DeleteTaskOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.deleteTaskRequest === null || requestParameters.deleteTaskRequest === undefined) {
            throw new runtime.RequiredError('deleteTaskRequest','Required parameter requestParameters.deleteTaskRequest was null or undefined when calling deleteTask.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tasks/delete`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteTaskRequestToJSON(requestParameters.deleteTaskRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Task
     */
    async deleteTask(requestParameters: DeleteTaskOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTaskRaw(requestParameters, initOverrides);
    }

    /**
     * Get Tasks
     */
    async getTasksRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTasksResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/tasks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTasksResponseFromJSON(jsonValue));
    }

    /**
     * Get Tasks
     */
    async getTasks(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTasksResponse> {
        const response = await this.getTasksRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update Task Completed Date
     */
    async updateTaskCompletedDateRaw(requestParameters: UpdateTaskCompletedDateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.updateTaskCompletedDateRequest === null || requestParameters.updateTaskCompletedDateRequest === undefined) {
            throw new runtime.RequiredError('updateTaskCompletedDateRequest','Required parameter requestParameters.updateTaskCompletedDateRequest was null or undefined when calling updateTaskCompletedDate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tasks/update/completed_date`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTaskCompletedDateRequestToJSON(requestParameters.updateTaskCompletedDateRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Task Completed Date
     */
    async updateTaskCompletedDate(requestParameters: UpdateTaskCompletedDateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateTaskCompletedDateRaw(requestParameters, initOverrides);
    }

    /**
     * Update Task Name
     */
    async updateTaskNameRaw(requestParameters: UpdateTaskNameOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.updateTaskNameRequest === null || requestParameters.updateTaskNameRequest === undefined) {
            throw new runtime.RequiredError('updateTaskNameRequest','Required parameter requestParameters.updateTaskNameRequest was null or undefined when calling updateTaskName.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/tasks/update/name`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTaskNameRequestToJSON(requestParameters.updateTaskNameRequest),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update Task Name
     */
    async updateTaskName(requestParameters: UpdateTaskNameOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updateTaskNameRaw(requestParameters, initOverrides);
    }

}
